# Proyecto de Modelación y Simulación

#### Se importan las librerías a utilizar.

In [1]:
import numpy as np
import random
import math

#### Se ingresa el sudoku que se desea resolver.

In [2]:
                   # 1  2  3  4  5  6  7  8  9
inicial = np.array([[1, 0, 3, 0, 6, 5, 0, 0, 0],   #1
                    [7, 0, 0, 0, 2, 0, 0, 0, 0],   #2
                    [5, 0, 0, 3, 0, 0, 0, 0, 0],   #3
                    [0, 0, 2, 6, 5, 0, 0, 3, 0],   #4
                    [0, 0, 1, 4, 3, 0, 6, 0, 0],   #5
                    [0, 0, 0, 0, 1, 7, 2, 0, 5],   #6
                    [0, 0, 0, 0, 0, 6, 0, 5, 0],   #7
                    [0, 0, 4, 0, 8, 0, 0, 6, 0],   #8
                    [0, 6, 0, 0, 4, 0, 0, 1, 0]])  #9

#### Se realiza una función que determina las posiciones (fila, columna) que son mutables, agrupando por subcuadro.

In [3]:
# Función que devuelve un arreglo de las posiciones mutables del sudoku.
def posiciones_mutables():
    mutables = [] # Lista donde se almacenan las posiciones mutables de cada subcuadrado.
    for fila in range(0, 9, 3): # Recorre las filas de todo el cuadro.
        for columna in range(0, 9, 3): # Recorre las columnas de todo el cuadro.
            posiciones = [] # Lista que almacena las posiciones mutables del subcuadrado analizado.
            for x in range(fila, fila + 3): # Recorre las filas del subcuadrado.
                for y in range(columna, columna + 3): # Recorre las columnas del subcuadrado.
                    if inicial[x, y] == 0: # Define si la celda se puede mutar.
                        posiciones.append((x, y))
            mutables.append(posiciones)
    return mutables # Lista con posiciones mutables.

mutables = posiciones_mutables() # Matriz con las posiciones mutables.

#### Se realiza una función que determina los números que faltan en un arreglo.

In [4]:
# Se establece un arreglo con los números que debe tener un arreglo del sudoku.
numeros = np.arange(1, 10)

# Función que devuelve una lista con los número que le faltan a un arreglo de entrada.
def numeros_faltantes(arreglo):
    return list(set(numeros) - set(arreglo)) # Se calcula la diferencia de conjuntos para determinar los faltantes.

# Se genera una lista con las listas de números faltantes en cada subcuadro.
faltantes = [numeros_faltantes(inicial[f:f+3, c:c+3].flatten()) for f in range(0, 9, 3) for c in range(0, 9, 3)]

### Funciones que generan la población inicial.

#### Se realiza una función que permite crear un individuo nuevo.

In [5]:
# Función que crea un nuevo individuo dejando invariantes las celdas iniciales.
def individuo_nuevo(ind):
    cont = 0 # Contador que permite recorrer las listas de faltantes de los sucuadros.
    for f in range(0, 9, 3): # Recorre las filas de todo el cuadro.
        for c in range(0, 9, 3): # Recorre las columnas de todo el cuadro.
            faltante = faltantes[cont][:] # Se define la lista de números del subcuadro.
            cont2 = 0 # Se define un contador que asegura que todos los fatantes serán usados.
            random.shuffle(faltante) # Se ordenan los faltantes de forma aleatoria.
            for x in range(f, f + 3): # Recorre las filas de los subcuadros.
                for y in range(c, c + 3): # Recorre las columnas de los subcuadros.
                    if inicial[x, y] == 0: # Condición de que falta un número.
                        ind[x, y] = faltante[cont2] # Se asigna un número faltante.
                        cont2 += 1
            cont += 1
    return ind.astype(int)

#### Se realiza una función que permite crear la población inicial.

In [6]:
# Función que develve una lista de tamaño n con nuevos individuos.
def poblacion_inicial(n):
    return [individuo_nuevo(inicial.copy()) for x in range(n)]

### Funciones Fitness.

#### Se realiza una función que determina la nota de un arreglo.

In [7]:
# Función que devuelve un número del 1 al 9 que indica la nota del arreglo.
def nota_arreglo(arreglo):
    return 9 - np.unique(arreglo).size # Es la cantidad de números repetidos en un arreglo.

#### Se realiza una función que determina la nota de un individuo.

In [8]:
# Función que determina la nota de un individuo, mediante las notas de sus columnas y fils.
def nota_individuo(ind):
    nota_neg = 0 # Almacena la nota que determina la cantidad de valores repetidos.
    nota_neg = sum(nota_arreglo(ind[:, j]) for j in range(9)) # La cantidad de valores repetidos por columna en todas las columnas.
    nota_neg += sum(nota_arreglo(ind[i, :]) for i in range(9)) # La cantidad de valores repetidos por fila en todas las filas.
    return 162 - nota_neg # Devuelve la nota del individuo.

#### Se realiza una función que determina las notas de la población.

In [9]:
# Función que devuelve una lista con las notas de cada individuo de la población.
def notas_individuos(poblacion):
    return [nota_individuo(x) for x in poblacion]

### Funciones de Selección.

#### Se realiza una función que determina los m individuos con notas más altas.

In [10]:
# Función que devuelve las posiciones correspondientes a las mejores notas.
def topm(notas, m):
    enumerada = list(enumerate(notas)) # lista de enumerados.
    enumerada.sort(key=lambda x: x[1], reverse=True) # Se ordena en función de los valores de las notas.
    return [idx for idx, valor in enumerada[:m]] # Se devuelve los m índices correspondientes a las notas más altas.

#### Se realiza una función que permite seleccionar individuos de la población.

In [11]:
# Función que selecciona individuos de la población.
def seleccion(poblacion, notas, m, torneo, elites, aleatorios):
    n = len(poblacion) # Número de individuos.
    mejores = int(m*elites) # Cantidad de mejores individuos a elegir.
    azar = int(m*aleatorios) # Cantidad de individuos al azar a elegir.
    torneos = m - mejores - azar # Cantidad de individuos elegidos por torneo.
    
    elegidos = [poblacion[i] for i in topm(notas, mejores)] # Elegidos por mejores notas.

    elegidos_azar = random.choices(poblacion, k=azar) # Elegidos al azar.
    for i in elegidos_azar:
        elegidos.append(i)

    for _ in range(torneos): # Elección por torneo.
        cand = random.sample(range(n), min(torneo, n)) # Se eligen candidatos al azar.
        ganador = max(cand, key=lambda i: notas[i]) # Elegimos al de mejor nota entre los candidatos.
        elegidos.append(poblacion[ganador])
        
    return elegidos # Listado de individuos elegidos.

### Funciones de cruce.

#### Se realiza una función que genera el cruce entre los individuos seleccionados.

In [12]:
# Función que permite cruzar los individuos seleccionados.
def cruzar(elegidos, n):
    m = len(elegidos) # Número de elegidos.
    hijos = [] # Lista donde se almacenará la nueva generación.
    
    for _ in range(n): # Ciclo que permite crear n individuos a partir del cruce.
        nuevo = np.zeros((9, 9), dtype = int) # 
        for f in range(0, 9, 3): # Recorre las filas de los subcuadros.
            for c in range(0, 9, 3): # Recorre las columnas de los subcuadros.
                nuevo[f:f+3, c:c+3] = random.choices(elegidos, k=1)[0][f:f+3, c:c+3] # Se asigna un subcuadro al hijo.
        hijos.append(nuevo)
    return hijos # Se devuelve los individuos de la nueva generación.

### Funciones de mutación.

#### Se realiza una función que permite mutar a un individuo.

In [13]:
# Función que permite mutar un individuo.
def mutar(individuo, d):
    for _ in range(d): # La cantidad de mutaciones requeridas.
        (f1, c1), (f2, c2) = random.sample(mutables[random.randint(0, 8)], 2) # Índices de las celdas a mutar.
        individuo[f1, c1], individuo[f2, c2] = individuo[f2, c2], individuo[f1, c1]  # Realiza el cambio de valores de celdas de un mismo subcuadro.
    return individuo # Devuelve al individuo mutado.

#### Se realiza una función que permite mutar a cada individuo de la población.

In [14]:
# Función que muta a todos los individuos de la población.
def mutar_poblacion(poblacion, d):
    for j in range(len(poblacion)): # Ciclo para recorrer a todos los individuos.
        poblacion[j] = mutar(poblacion[j], d) # Se muta al individuo.
    return poblacion # Se devuelve la población mutada.

### Algoritmo genético

In [15]:
def sudoku_genetico(n, m, d, max_gen = 5000, torneo = 3, elites = 0.6, aleatorios = 0.2):
    
    random.seed(10) # Semilla aleatoria.

    generacion, reinicio, maxima_nota, cambio_mutacion = 0, 0, 0, 1# Se definen contadores y variables almacenadoras de resultados.
    elit = int(m*elites) 
    reiniciar = int(max_gen*0.1)

    poblacion = poblacion_inicial(n) # Se realiza la primera iteración de la población.
    mutables = posiciones_mutables()
    notas = notas_individuos(poblacion)
    elegidos = seleccion(poblacion, notas, m, torneo, elites, aleatorios)

    mejor_nota = max(notas) # Se almacena las características de mejor individuo.
    mejor_ind = elegidos[0]


    while maxima_nota < 162 and generacion < max_gen: # Se recorren nuevas generaciones.

        mejores_ind =  elegidos[:elit] # Se crea la nueva generación.
        hijos = cruzar(elegidos, n - m)
        mutados = mutar_poblacion(hijos + elegidos[elit:], d)
        poblacion = mejores_ind + mutados
        notas = notas_individuos(poblacion)
        elegidos = seleccion(poblacion, notas, m, torneo, elites, aleatorios)
        
        if max(notas) > maxima_nota: # Se realizan cambios en caso de que se haya encontrado un nuevo mejor individuo.
            maxima_nota = max(notas)
            mejor_ind = elegidos[0].copy()
            cambio_mutacion, reinicio = 1, 0
            print(generacion, maxima_nota)
            
        if reinicio == reiniciar: # En caso de que no se obtengan cambios se realiza una mutación completa a todos los individuos.
            poblacion = mutar_poblacion(poblacion, cambio_mutacion * d)
            cambio_mutacion += 1
            reinicio = 0
        
        generacion += 1 # Iteradores.
        reinicio +=1 
        
    return generacion, mejor_ind, maxima_nota # Se devuelve la generación, el mejor individuo y su nota.

### Generación de la solución

In [16]:
#gen, sol_mio, nota = sudoku_genetico(n = 100, m = 15, d = 2, max_gen = 5000, torneo = 3, elites = 0.3, aleatorios = 0.1)
gen, sol_mio, nota = sudoku_genetico(n = 150, m = 40, d = 2, max_gen = 5000, torneo = 4, elites = 0.3, aleatorios = 0.4)
gen, sol_mio, nota

0 136
3 138
5 140
6 141
10 142
11 144
13 146
20 147
22 148
24 149
28 151
39 152
56 153
123 154
195 156
246 158
807 159
834 160
2743 162


(2744,
 array([[1, 2, 3, 8, 6, 5, 4, 9, 7],
        [7, 4, 6, 1, 2, 9, 5, 8, 3],
        [5, 8, 9, 3, 7, 4, 1, 2, 6],
        [4, 7, 2, 6, 5, 8, 9, 3, 1],
        [9, 5, 1, 4, 3, 2, 6, 7, 8],
        [6, 3, 8, 9, 1, 7, 2, 4, 5],
        [8, 1, 7, 2, 9, 6, 3, 5, 4],
        [3, 9, 4, 5, 8, 1, 7, 6, 2],
        [2, 6, 5, 7, 4, 3, 8, 1, 9]]),
 162)

### Corroboración

In [17]:
               # 1  2  3  4  5  6  7  8  9
sol = np.array([[1, 2, 3, 8, 6, 5, 4, 9, 7], # 1
                [7, 4, 6, 1, 2, 9, 5, 8, 3], # 2
                [5, 8, 9, 3, 7, 4, 1, 2, 6], # 3
                [4, 7, 2, 6, 5, 8, 9, 3, 1], # 4
                [9, 5, 1, 4, 3, 2, 6, 7, 8], # 5
                [6, 3, 8, 9, 1, 7, 2, 4, 5], # 6
                [8, 1, 7, 2, 9, 6, 3, 5, 4], # 7
                [3, 9, 4, 5, 8, 1, 7, 6, 2], # 8
                [2, 6, 5, 7, 4, 3, 8, 1, 9]]) # 9

In [18]:
sol_mio - sol

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

CasoI:reducción de la población (n) con el número de elegidos m=15

n=100

In [19]:
gen, sol_mio, nota = sudoku_genetico(n = 100, m = 15, d = 2, max_gen = 5000, torneo = 3, elites = 0.3, aleatorios = 0.1)
gen, sol_mio, nota

0 129
1 136
3 138
4 139
5 140
6 141
7 142
12 143
14 144
15 146
21 147
32 148
33 149
39 151
45 152
48 153
54 154
63 156
124 157
130 158
202 159
352 160
901 162


(902,
 array([[1, 2, 3, 8, 6, 5, 4, 9, 7],
        [7, 4, 6, 1, 2, 9, 5, 8, 3],
        [5, 8, 9, 3, 7, 4, 1, 2, 6],
        [4, 7, 2, 6, 5, 8, 9, 3, 1],
        [9, 5, 1, 4, 3, 2, 6, 7, 8],
        [6, 3, 8, 9, 1, 7, 2, 4, 5],
        [8, 1, 7, 2, 9, 6, 3, 5, 4],
        [3, 9, 4, 5, 8, 1, 7, 6, 2],
        [2, 6, 5, 7, 4, 3, 8, 1, 9]]),
 162)

n=50

In [20]:
gen, sol_mio, nota = sudoku_genetico(n = 50, m = 15, d = 2, max_gen = 5000, torneo = 3, elites = 0.3, aleatorios = 0.1)
gen, sol_mio, nota

0 134
4 136
5 138
6 140
9 141
10 144
13 145
17 146
20 147
21 148
41 150
48 151
50 152
88 153
113 154
293 158
1082 159
2774 160


(5000,
 array([[1, 2, 3, 8, 6, 5, 4, 9, 7],
        [7, 4, 6, 1, 2, 9, 5, 8, 3],
        [5, 8, 9, 3, 7, 4, 1, 2, 6],
        [4, 7, 2, 6, 5, 8, 9, 3, 1],
        [9, 5, 1, 4, 3, 2, 6, 7, 8],
        [6, 3, 8, 9, 1, 7, 2, 4, 5],
        [3, 1, 7, 2, 9, 6, 7, 5, 4],
        [8, 9, 4, 5, 8, 1, 3, 6, 2],
        [2, 6, 5, 7, 4, 3, 8, 1, 9]]),
 160)

n=30

In [21]:
gen, sol_mio, nota = sudoku_genetico(n = 30, m = 15, d = 2, max_gen = 5000, torneo = 3, elites = 0.3, aleatorios = 0.1)
gen, sol_mio, nota

0 131
1 132
2 137
3 138
9 140
11 142
13 143
25 144
28 146
44 149
235 150
240 151
667 152
711 153
3447 154


(5000,
 array([[1, 8, 3, 9, 6, 5, 4, 8, 7],
        [7, 4, 6, 8, 2, 1, 5, 9, 3],
        [5, 2, 9, 3, 7, 4, 1, 2, 6],
        [4, 5, 2, 6, 5, 8, 9, 3, 1],
        [6, 7, 1, 4, 3, 9, 6, 7, 8],
        [9, 3, 8, 2, 1, 7, 2, 4, 5],
        [8, 1, 7, 5, 9, 6, 3, 5, 2],
        [2, 9, 4, 1, 8, 3, 7, 6, 4],
        [3, 6, 5, 7, 4, 2, 8, 1, 9]]),
 154)

n=20

In [22]:
gen, sol_mio, nota = sudoku_genetico(n = 20, m = 15, d = 2, max_gen = 5000, torneo = 3, elites = 0.3, aleatorios = 0.1)
gen, sol_mio, nota

0 126
1 129
3 130
4 131
5 133
8 134
12 135
13 137
22 138
39 139
43 141
74 142
101 144
1651 145
4604 146


(5000,
 array([[1, 8, 3, 7, 6, 5, 9, 5, 3],
        [7, 9, 2, 8, 2, 4, 1, 7, 6],
        [5, 4, 6, 3, 9, 1, 4, 2, 8],
        [4, 7, 2, 6, 5, 8, 9, 3, 1],
        [9, 5, 1, 4, 3, 2, 6, 8, 7],
        [3, 6, 8, 9, 1, 7, 2, 4, 5],
        [8, 2, 7, 1, 7, 6, 3, 5, 9],
        [5, 1, 4, 9, 8, 3, 7, 6, 4],
        [3, 6, 9, 5, 4, 2, 8, 1, 2]]),
 146)

n=10

In [23]:
gen, sol_mio, nota = sudoku_genetico(n = 10, m = 15, d = 2, max_gen = 5000, torneo = 3, elites = 0.3, aleatorios = 0.1)
gen, sol_mio, nota

0 126
5 127
44 128
63 129
109 130
800 134
2817 137


(5000,
 array([[1, 2, 3, 8, 6, 5, 6, 8, 7],
        [7, 6, 4, 7, 2, 1, 4, 9, 3],
        [5, 8, 9, 3, 9, 4, 5, 2, 1],
        [4, 6, 2, 6, 5, 8, 1, 3, 7],
        [7, 8, 1, 4, 3, 2, 6, 4, 9],
        [9, 3, 5, 9, 1, 7, 2, 8, 5],
        [8, 5, 9, 1, 7, 6, 3, 5, 4],
        [2, 1, 4, 5, 8, 9, 7, 6, 8],
        [3, 6, 7, 2, 4, 3, 2, 1, 9]]),
 137)

Aumento de población n

n=200

In [24]:
gen, sol_mio, nota = sudoku_genetico(n = 200, m = 15, d = 2, max_gen = 5000, torneo = 3, elites = 0.3, aleatorios = 0.1)
gen, sol_mio, nota

0 136
1 137
3 139
5 143
6 144
11 145
13 147
16 148
24 150
29 151
59 152
95 153
97 154
157 156
584 157
590 158
2655 159
2678 160


(5000,
 array([[1, 8, 3, 9, 6, 5, 7, 2, 4],
        [7, 4, 6, 1, 2, 8, 5, 9, 3],
        [5, 2, 9, 3, 7, 4, 1, 8, 6],
        [4, 7, 2, 6, 5, 9, 8, 3, 1],
        [8, 5, 1, 4, 3, 2, 6, 7, 9],
        [6, 3, 9, 8, 1, 7, 2, 4, 5],
        [3, 1, 7, 2, 9, 6, 4, 5, 8],
        [2, 9, 4, 5, 8, 1, 3, 6, 7],
        [8, 6, 5, 7, 4, 3, 9, 1, 2]]),
 160)

n=250

In [25]:
gen, sol_mio, nota = sudoku_genetico(n = 250, m = 15, d = 2, max_gen = 5000, torneo = 3, elites = 0.3, aleatorios = 0.1)
gen, sol_mio, nota

0 133
1 135
2 137
3 138
4 140
5 142
6 143
7 146
8 147
9 148
10 149
12 150
13 152
25 154
56 155
61 156
315 158


(5000,
 array([[1, 4, 3, 8, 6, 5, 9, 2, 7],
        [7, 8, 6, 9, 2, 1, 5, 4, 3],
        [5, 2, 9, 3, 7, 4, 1, 8, 6],
        [9, 7, 2, 6, 5, 8, 4, 3, 1],
        [6, 5, 1, 4, 3, 9, 6, 7, 8],
        [4, 3, 8, 2, 1, 7, 2, 9, 5],
        [8, 1, 5, 7, 9, 6, 3, 5, 2],
        [3, 9, 4, 1, 8, 2, 7, 6, 4],
        [2, 6, 7, 5, 4, 3, 8, 1, 9]]),
 158)

n=300

In [26]:
gen, sol_mio, nota = sudoku_genetico(n = 300, m = 15, d = 2, max_gen = 5000, torneo = 3, elites = 0.3, aleatorios = 0.1)
gen, sol_mio, nota

0 136
2 139
3 140
4 142
5 144
6 145
8 147
11 148
12 149
17 152
21 153
22 154
23 155
44 156
53 158


(5000,
 array([[1, 2, 3, 8, 6, 5, 3, 9, 4],
        [7, 4, 9, 7, 2, 1, 5, 8, 6],
        [5, 8, 6, 3, 9, 4, 1, 2, 7],
        [4, 7, 2, 6, 5, 8, 9, 3, 1],
        [9, 5, 1, 4, 3, 2, 6, 7, 8],
        [6, 3, 8, 9, 1, 7, 2, 4, 5],
        [2, 9, 8, 1, 7, 6, 4, 5, 3],
        [3, 1, 4, 5, 8, 9, 7, 6, 2],
        [7, 6, 5, 2, 4, 3, 8, 1, 9]]),
 158)

n=350

In [27]:
gen, sol_mio, nota = sudoku_genetico(n = 350, m = 15, d = 2, max_gen = 5000, torneo = 3, elites = 0.3, aleatorios = 0.1)
gen, sol_mio, nota

0 136
1 138
3 139
4 141
5 142
6 143
8 146
9 147
12 150
14 153
20 156
29 157
32 158
35 160
211 162


(212,
 array([[1, 2, 3, 8, 6, 5, 4, 9, 7],
        [7, 4, 6, 1, 2, 9, 5, 8, 3],
        [5, 8, 9, 3, 7, 4, 1, 2, 6],
        [4, 7, 2, 6, 5, 8, 9, 3, 1],
        [9, 5, 1, 4, 3, 2, 6, 7, 8],
        [6, 3, 8, 9, 1, 7, 2, 4, 5],
        [8, 1, 7, 2, 9, 6, 3, 5, 4],
        [3, 9, 4, 5, 8, 1, 7, 6, 2],
        [2, 6, 5, 7, 4, 3, 8, 1, 9]]),
 162)

Caso: disminución de individuos elegidos de la población

m=30

In [28]:
gen, sol_mio, nota = sudoku_genetico(n = 150, m = 30, d = 2, max_gen = 5000, torneo = 4, elites = 0.3, aleatorios = 0.4)
gen, sol_mio, nota

0 136
2 139
5 140
8 142
10 143
11 144
12 146
16 147
20 148
23 149
27 150
47 152
78 153
95 155
119 156
148 158
646 160


(5000,
 array([[1, 2, 3, 8, 6, 5, 4, 9, 7],
        [7, 4, 6, 9, 2, 1, 5, 8, 3],
        [5, 9, 8, 3, 7, 4, 1, 2, 6],
        [4, 7, 2, 6, 5, 8, 9, 3, 1],
        [6, 5, 1, 4, 3, 9, 6, 7, 8],
        [8, 3, 9, 2, 1, 7, 2, 4, 5],
        [2, 8, 7, 1, 9, 6, 3, 5, 4],
        [3, 1, 4, 5, 8, 2, 7, 6, 9],
        [9, 6, 5, 7, 4, 3, 8, 1, 2]]),
 160)

m=20

In [29]:
gen, sol_mio, nota = sudoku_genetico(n = 150, m = 20, d = 2, max_gen = 5000, torneo = 4, elites = 0.3, aleatorios = 0.4)
gen, sol_mio, nota

0 136
2 137
3 138
4 139
5 141
6 142
7 145
19 148
34 149
35 150
41 151
47 152
79 153
110 154
125 156
456 157
580 158
1046 160


(5000,
 array([[1, 8, 3, 7, 6, 5, 4, 2, 9],
        [7, 9, 6, 1, 2, 4, 5, 8, 3],
        [5, 4, 2, 3, 9, 8, 1, 7, 6],
        [4, 7, 2, 6, 5, 9, 8, 3, 1],
        [8, 5, 1, 4, 3, 2, 6, 9, 7],
        [6, 3, 9, 8, 1, 7, 2, 4, 5],
        [9, 1, 8, 2, 7, 6, 3, 5, 4],
        [3, 5, 4, 9, 8, 1, 7, 6, 2],
        [2, 6, 7, 5, 4, 3, 9, 1, 8]]),
 160)

m=10

In [30]:
gen, sol_mio, nota = sudoku_genetico(n = 150, m = 10, d = 2, max_gen = 5000, torneo = 4, elites = 0.3, aleatorios = 0.4)
gen, sol_mio, nota

0 136
4 139
5 140
7 141
8 142
10 144
14 146
16 148
20 149
30 150
32 151
50 152
60 153
77 154
103 156
1561 158
2442 160


(5000,
 array([[1, 4, 3, 7, 6, 5, 9, 2, 8],
        [7, 9, 6, 8, 2, 1, 5, 4, 3],
        [5, 2, 8, 3, 9, 4, 1, 7, 6],
        [9, 7, 2, 6, 5, 8, 4, 3, 1],
        [8, 5, 1, 4, 3, 2, 6, 9, 7],
        [6, 3, 4, 9, 1, 7, 2, 8, 5],
        [2, 8, 9, 1, 7, 6, 3, 5, 4],
        [3, 1, 4, 5, 8, 9, 7, 6, 2],
        [7, 6, 5, 2, 4, 3, 8, 1, 9]]),
 160)

m=5

In [31]:
gen, sol_mio, nota = sudoku_genetico(n = 150, m = 5, d = 2, max_gen = 5000, torneo = 4, elites = 0.3, aleatorios = 0.4)
gen, sol_mio, nota

0 136
2 137
5 139
6 140
8 142
10 143
14 144
18 147
19 148
20 149
32 150
39 151
86 152
166 153
243 154
788 155
988 156
1687 157
3222 158


(5000,
 array([[1, 2, 3, 8, 6, 5, 4, 9, 7],
        [7, 4, 6, 1, 2, 9, 5, 8, 3],
        [5, 9, 8, 3, 7, 4, 1, 2, 6],
        [4, 7, 2, 6, 5, 8, 9, 3, 1],
        [9, 5, 1, 4, 3, 2, 6, 7, 8],
        [6, 8, 3, 9, 1, 7, 2, 4, 5],
        [8, 1, 9, 2, 9, 6, 7, 5, 4],
        [2, 5, 4, 7, 8, 1, 3, 6, 9],
        [3, 6, 7, 5, 4, 3, 8, 1, 2]]),
 158)

Caso: Aumento de la cantidad de individuos elegidos

m=50

In [32]:
gen, sol_mio, nota = sudoku_genetico(n = 150, m = 50, d = 2, max_gen = 5000, torneo = 4, elites = 0.3, aleatorios = 0.4)
gen, sol_mio, nota

0 136
1 138
5 139
9 140
10 141
11 143
12 145
13 146
18 148
21 151
71 152
114 153
139 154
188 155
193 156
364 157
483 158
1670 160
2870 162


(2871,
 array([[1, 2, 3, 8, 6, 5, 4, 9, 7],
        [7, 4, 6, 1, 2, 9, 5, 8, 3],
        [5, 8, 9, 3, 7, 4, 1, 2, 6],
        [4, 7, 2, 6, 5, 8, 9, 3, 1],
        [9, 5, 1, 4, 3, 2, 6, 7, 8],
        [6, 3, 8, 9, 1, 7, 2, 4, 5],
        [8, 1, 7, 2, 9, 6, 3, 5, 4],
        [3, 9, 4, 5, 8, 1, 7, 6, 2],
        [2, 6, 5, 7, 4, 3, 8, 1, 9]]),
 162)

m=60

In [33]:
gen, sol_mio, nota = sudoku_genetico(n = 150, m = 60, d = 2, max_gen = 5000, torneo = 4, elites = 0.3, aleatorios = 0.4)
gen, sol_mio, nota

0 136
5 137
6 139
9 140
10 141
14 146
18 148
29 149
30 150
41 152
63 153
90 154
141 158
499 159
1064 160
2422 162


(2423,
 array([[1, 2, 3, 8, 6, 5, 4, 9, 7],
        [7, 4, 6, 1, 2, 9, 5, 8, 3],
        [5, 8, 9, 3, 7, 4, 1, 2, 6],
        [4, 7, 2, 6, 5, 8, 9, 3, 1],
        [9, 5, 1, 4, 3, 2, 6, 7, 8],
        [6, 3, 8, 9, 1, 7, 2, 4, 5],
        [8, 1, 7, 2, 9, 6, 3, 5, 4],
        [3, 9, 4, 5, 8, 1, 7, 6, 2],
        [2, 6, 5, 7, 4, 3, 8, 1, 9]]),
 162)

m=70

In [34]:
gen, sol_mio, nota = sudoku_genetico(n = 150, m = 70, d = 2, max_gen = 5000, torneo = 4, elites = 0.3, aleatorios = 0.4)
gen, sol_mio, nota

0 136
1 137
6 139
9 140
12 143
15 148
28 149
41 152
53 153
155 154
177 155
215 156
331 157
396 158
651 160
720 162


(721,
 array([[1, 2, 3, 8, 6, 5, 4, 9, 7],
        [7, 4, 6, 1, 2, 9, 5, 8, 3],
        [5, 8, 9, 3, 7, 4, 1, 2, 6],
        [4, 7, 2, 6, 5, 8, 9, 3, 1],
        [9, 5, 1, 4, 3, 2, 6, 7, 8],
        [6, 3, 8, 9, 1, 7, 2, 4, 5],
        [8, 1, 7, 2, 9, 6, 3, 5, 4],
        [3, 9, 4, 5, 8, 1, 7, 6, 2],
        [2, 6, 5, 7, 4, 3, 8, 1, 9]]),
 162)

m=80

In [35]:
gen, sol_mio, nota = sudoku_genetico(n = 150, m = 80, d = 2, max_gen = 5000, torneo = 4, elites = 0.3, aleatorios = 0.4)
gen, sol_mio, nota

0 136
3 137
5 139
10 141
19 142
20 143
24 148
30 149
33 150
37 153
92 154
216 155
224 156
455 158
4104 160


(5000,
 array([[1, 2, 3, 9, 6, 5, 4, 8, 7],
        [7, 8, 6, 1, 2, 4, 5, 9, 3],
        [5, 4, 9, 3, 7, 8, 1, 2, 6],
        [4, 7, 2, 6, 5, 8, 9, 3, 1],
        [9, 5, 1, 4, 3, 2, 6, 7, 8],
        [6, 3, 8, 9, 1, 7, 2, 4, 5],
        [8, 1, 7, 2, 9, 6, 3, 5, 4],
        [3, 9, 4, 5, 8, 1, 7, 6, 2],
        [2, 6, 5, 7, 4, 3, 8, 1, 9]]),
 160)